---
title: "Homework4"
format: html
editor: visual
---
## Calling Libraries

```{r}
library(tidyverse)
library(lubridate)
```


## Task1: Conceptual Questions






##Task 2: Reading Delimited Data

### Glass Data 

```{r}
glass<- read_delim("https://www4.stat.ncsu.edu/~online/datasets/glass.data",
                   delim=",",
                   col_names = c("ID","RI","Na","Mg","Al","Si","K","Ca","Ba","Fe","typ"))
glass|> mutate(typ2=ifelse(glass$typ==1,"Building_Windows_float_processed",
                ifelse(glass$typ==2,"Building_Windows_non_Float_Processed",
                       
                       
                               ifelse(glass$typ==3,"Vehicle_Windows_Float_Processed",
                                      ifelse(glass$typ==4,"Vehicle_Windows_Non_Float_Processed",
                                             ifelse(glass$typ==5,"Containers",
                                                    ifelse(glass$typ==6,"Tableware",
                                                           ifelse(glass$typ==7,"Headlamps","Other"))))   )
                           ) ) ) |>
  
               filter(Fe <0.2 & (typ2=='Tableware' | typ2=='Headlamps'))

```

### Yeast Data

```{r}
library(readr)
yeast<-read_table("https://www4.stat.ncsu.edu/online/datasets/yeast.data", col_names=c("seq_name","mcg","gvh","alm","mit","erl","pox","vac","nuc","class")
)

yeast

```

